### ISSUE TITLE
Any chance for a more thorough tutorial?

### ISSUE THREAD

**Issue by jamesalmeida** [TylerGlaiel/voicemask#1]
I’d love to build this but am a little lost with how exactly all the parts should go together. Any help with this would be appreciated. Keep up the awesome work!

**Comment by TylerGlaiel** [comment]
yeah I'm planning on writing up a more thorough tutorial this weekend

**Comment by jamesalmeida** [comment]
Yessssss! Thanks dude!

**Comment by TylerGlaiel** [comment]
https://medium.com/@tglaiel/how-to-make-a-voice-activated-led-facemask-diy-guide-b300bc146f38
