### ISSUE TITLE
Parts list

### ISSUE THREAD

**Issue by joel-g** [TylerGlaiel/voicemask#2]
I'm having trouble finding a flexible LED grid for sale. Any chance you could post a parts list with links? This would be a good opportunity to share some sponsored affiliate links

**Comment by TylerGlaiel** [comment]
yup I'm planning on doing that this weekend, here's an affiliate link for the LED panels I used in the mean time https://amzn.to/2ZOfNIM

**Comment by TylerGlaiel** [comment]
https://medium.com/@tglaiel/how-to-make-a-voice-activated-led-facemask-diy-guide-b300bc146f38
