### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by Vortex1470** [TylerGlaiel/voicemask#3]
I have been trying to flash your code onto a Aeduino but im getting about 12 error messages like seen bbelow VVV i have copied the code exact (Ctrl c + v) and installed the required libraries. 

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino: In function 'void loop()':

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:150:30: warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]

         drawImage(mouth_smile);

                              ^

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:84:6: note:   initializing argument 1 of 'void drawImage(short int)'

 void drawImage(short image_addr){

      ^~~~~~~~~

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:152:26: warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]

         drawImage(mouth_0);

                          ^

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:84:6: note:   initializing argument 1 of 'void drawImage(short int)'

 void drawImage(short image_addr){

      ^~~~~~~~~

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:154:26: warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]

         drawImage(mouth_1);

                          ^

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:84:6: note:   initializing argument 1 of 'void drawImage(short int)'

 void drawImage(short image_addr){

      ^~~~~~~~~

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:156:26: warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]

         drawImage(mouth_2);

                          ^

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:84:6: note:   initializing argument 1 of 'void drawImage(short int)'

 void drawImage(short image_addr){

      ^~~~~~~~~

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:158:26: warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]

         drawImage(mouth_3);

                          ^

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:84:6: note:   initializing argument 1 of 'void drawImage(short int)'

 void drawImage(short image_addr){

      ^~~~~~~~~

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:160:26: warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]

         drawImage(mouth_4);

                          ^

C:\Users\alexander\Documents\Arduino\sketch_jun12a\sketch_jun12a.ino:84:6: note:   initializing argument 1 of 'void drawImage(short int)'

 void drawImage(short image_addr){

      ^~~~~~~~~

Sketch uses 11594 bytes (37%) of program storage space. Maximum is 30720 bytes.
Global variables use 481 bytes (23%) of dynamic memory, leaving 1567 bytes for local variables. Maximum is 2048 bytes.

**Comment by TylerGlaiel** [comment]
those are warnings not errors, it should still work fine

**Comment by Vortex1470** [comment]
okay thank you i will close the issue if its done tommorow :)

**Comment by TylerGlaiel** [comment]
im leaving this issue open in case someone wants to submit a pull request with the warnings fixed

**Comment by gramster** [comment]
I'm getting an actual error:

Arduino: 1.8.12 (Mac OS X), Board: "Arduino Nano, ATmega328P"

In file included from /Users/gram/Documents/Arduino/sketch_jun18a/sketch_jun18a.ino:9:0:
/Users/gram/Documents/Arduino/libraries/Adafruit_NeoPixel/Adafruit_NeoPixel.h:151:52: error: redefinition of 'const uint8_t _NeoPixelSineTable [256]'
 static const uint8_t PROGMEM _NeoPixelSineTable[256] = {
                                                    ^

**Comment by IreneGonzalezGonzalez** [comment]
Hi! Thank you very much for your code!
I am having the same problem as Vortex 1470 : 
 invalid conversion from 'const uint8_t ()[8] {aka const unsigned char ()[8]}' to 'short int' [-fpermissive]
in:
drawImage(mouth_smile);
drawImage(mouth_0);
drawImage(mouth_1);
drawImage(mouth_2);
drawImage(mouth_3);
drawImage(mouth_4);

They are not warnings but error that do not allow me to upload the code to my board.
I would really appreacite some help, thanks :)

**Comment by scottishsurfer** [comment]
Yeah, I get the same error/warning messages when trying to Verify the code before uploading.

warning: invalid conversion from 'const uint8_t (*)[8] {aka const unsigned char (*)[8]}' to 'short int' [-fpermissive]
         drawImage(mouth_smile);

**Comment by scottishsurfer** [comment]
Ok Tyler, you are right.  These are just warnings that anyone can fix if they want, but not required.

**Comment by TylerGlaiel** [comment]
fixed the warnings
