### ISSUE TITLE
Mask Project

### ISSUE THREAD

**Issue by raquel-pascual** [TylerGlaiel/voicemask#4]
Hi Tyler!

First of all, thank you so much for your project! It's so much fun! I'm from Spain, and my husband and I have decided to do it. It's our first Arduino project. I have a question with the code. I have download the software and I have copy the whole thing (starting with #include <Adafruit_NeoPixel.h> until the end. And it's giving some errors:

Arduino:1.8.12 (Windows 10), Tarjeta:"Arduino Nano, ATmega328P"

Mascarilla:1:10: fatal error: Adafruit_NeoPixel.h: No such file or directory

 #include <Adafruit_NeoPixel.h>

          ^~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1
Adafruit_NeoPixel.h: No such file or directory

And, after this, it gives me some more errors, saying "No such file or directory".

Could you please help me? It's the first time and we have no idea at all.

We will be very thankful.

Thank you very much.

Best wishes,

Raquel and Caleb

**Comment by NichaT** [comment]
Try uploading through the "Arduino Web Editor". 

1. Download the "Arduino create"
2. Install the plugin and open it.
3. When opening it, you'll be directed to https://create.arduino.cc/
4. Choose Arduino Web Editor
5. Select:
Board: Arduino Nano
Ports: (Find this in Control Panel/Device Manager)
Flavours: ATmega328P (Old Bootloader)

**Comment by TylerGlaiel** [comment]
https://www.arduino.cc/en/guide/libraries

**Comment by TylerGlaiel** [comment]
added a comment to the code specifying that you need to include the libraries in the arduino IDE as well
