### ISSUE TITLE
LED mouth position rapid flickering.

### ISSUE THREAD

**Issue by mikeouwen** [TylerGlaiel/voicemask#5]
Thanks for sharing this project. I've managed to make one. But sometimes the mouth will rapidly flicker between different mouse positions even though it should be in the silent state.

I'm still not able to pinpoint the cause. Another thing to note is that I was powering it with a 9V battery and the voltage between VIN pin and GND pin is just 4V. Not sure if it's normal. I checked the voltage of the battery and it's a solid 9V.

Here is what the symptom looks like https://youtu.be/j9fEsU-NkNE

**Comment by TylerGlaiel** [comment]
check your wiring and check the adjustable gain screw on the back of the microphone

it could be a faulty electrical component as well

**Comment by mikeouwen** [comment]
> check your wiring and check the adjustable gain screw on the back of the microphone
> 
> it could be a faulty electrical component as well

Thank you Tyler. Turns out to be the battery problem. I bought some new ones and they give a solid 9V between VIN and GND. Everything smooth now. 

Still not sure why the old battery gives only 4V between VIN and GND. Maybe it's because of the low max amp they can give out.
